name: Python Pytest testing

on:
    pull_request:
        branches:
            - develop
            - live
            - feature/*

jobs:
    test:
        runs-on: ubuntu-latest
        steps: 
            # checkouut the repo
            - uses: actions/checkout@v3
            # set up python
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: "3.x"
            # install requirements.txt
            - name: install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            # run pytest
            - name: Test with pytest
              run: pytest